const asyncHandler = require('express-async-handler');
const Project = require('../models/Project');
const Bid = require('../models/Bid');

// @desc    Create a new project (generated by AI and confirmed by user)
// @route   POST /api/projects
// @access  Private (User)
const createProject = asyncHandler(async (req, res) => {
  const { title, description, scopeOfWork, estimatedBudget, location } = req.body;

  const project = new Project({
    user: req.user._id,
    title,
    description,
    scopeOfWork,
    estimatedBudget,
    location,
  });

  const createdProject = await project.save();
  res.status(201).json(createdProject);
});

// @desc    Get all open projects (for contractors)
// @route   GET /api/projects
// @access  Private (Contractor)
const getProjects = asyncHandler(async (req, res) => {
  const projects = await Project.find({ status: 'open' }).populate('user', 'name');
  res.json(projects);
});

// @desc    Get user's own projects
// @route   GET /api/projects/myprojects
// @access  Private (User)
const getMyProjects = asyncHandler(async (req, res) => {
  const projects = await Project.find({ user: req.user._id }).populate('acceptedBid');
  res.json(projects);
});

// @desc    Get single project
// @route   GET /api/projects/:id
// @access  Private
const getProjectById = asyncHandler(async (req, res) => {
  const project = await Project.findById(req.params.id)
    .populate('user', 'name')
    .populate({
        path: 'acceptedBid',
        populate: {
            path: 'contractor',
            select: 'name email phone experienceYears portfolioDescription'
        }
    });

  if (project) {
    res.json(project);
  } else {
    res.status(404);
    throw new Error('Project not found');
  }
});

// @desc    Submit a bid for a project
// @route   POST /api/projects/:id/bids
// @access  Private (Contractor)
const submitBid = asyncHandler(async (req, res) => {
  const { amount, proposal } = req.body;
  const projectId = req.params.id;

  const project = await Project.findById(projectId);

  if (!project) {
    res.status(404);
    throw new Error('Project not found');
  }

  // Check if contractor already bidded
  const alreadyBidded = await Bid.findOne({ project: projectId, contractor: req.user._id });
  if (alreadyBidded) {
    res.status(400);
    throw new Error('You already submitted a bid for this project');
  }

  const bid = new Bid({
    project: projectId,
    contractor: req.user._id,
    amount,
    proposal,
  });

  const createdBid = await bid.save();
  res.status(201).json(createdBid);
});

// @desc    Get all bids for a project
// @route   GET /api/projects/:id/bids
// @access  Private (User)
const getProjectBids = asyncHandler(async (req, res) => {
  const bids = await Bid.find({ project: req.params.id }).populate('contractor', 'name experienceYears portfolioDescription');
  res.json(bids);
});

// @desc    Accept a bid
// @route   PUT /api/projects/:id/bids/:bidId/accept
// @access  Private (User)
const acceptBid = asyncHandler(async (req, res) => {
  const project = await Project.findById(req.params.id);
  const bid = await Bid.findById(req.params.bidId);

  if (!project || !bid) {
    res.status(404);
    throw new Error('Project or Bid not found');
  }

  if (project.user.toString() !== req.user._id.toString()) {
    res.status(401);
    throw new Error('Not authorized');
  }

  // Update bid status
  bid.status = 'accepted';
  await bid.save();

  // Reject all other bids
  await Bid.updateMany(
    { project: req.params.id, _id: { $ne: req.params.bidId } },
    { $set: { status: 'rejected' } }
  );

  // Update project
  project.status = 'accepted';
  project.acceptedBid = bid._id;
  await project.save();

  res.json({ message: 'Bid accepted', project });
});

module.exports = {
  createProject,
  getProjects,
  getMyProjects,
  getProjectById,
  submitBid,
  getProjectBids,
  acceptBid,
};
